[package]
name = "sandsim"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
getrandom = { version = "0.3.3", features = ["wasm_js"] }
rand = "0.9.2"
[lib]
name = "sandsim"
path = "src/lib.rs"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
